   title: "Baymax LLM"
   format: pdf
   geometry:
         - top=30mm
         - left=20mm
         - right=20mm
         - bottom=30mm
   fontsize: 11pt
   colorlinks: true
   toc: true
   number-sections: true